- src/Commands/bgm.ts
- src/Commands/commands.ts
- src/Commands/index.ts
- src/Commands/leaveclean.ts
- src/Commands/lyrics.ts
- src/Commands/mltf.ts
- src/Commands/play.ts
- src/Commands/reboot.ts
- src/Commands/related.ts
- src/Commands/reset.ts
- src/Commands/rm.ts
- src/Commands/rmall.ts
- src/Commands/skip.ts
- src/Commands/uptime.ts
> Command画面の動的生成

- package-lock.json
- package.json
> Update: Bump discord.js from 13.5.1 to 13.6.0

- README.md
`npm onlystart` → `npm run onlystart`
> Fix: fix typo

- src/Commands/index.ts
- src/Commands/systeminfo.ts
- util/registercommands/register.js
improvement of log command
this allows users to get more system infos with lesser messages
> Feat: log system basic info

- src/Commands/equallypb.ts
- src/Commands/queue.ts
- src/Component/QueueManager.ts
- src/Util/colorUtil.ts
- src/bot.ts
- src/definition.ts
> Feat: equally playback

- package-lock.json
- package.json
- tsconfig.json
> Improve: configure to use tslib

- .github/dependabot.yml
is it confugurable? - I don't know - OK let's experiment
> Chore(dependabot.yml): multiple branches

- src/Commands/export.ts
- src/Commands/invoke.ts
- src/Util/general.ts
... and some minor bug fixes and improvements
> Fix: invalid link on export command

- src/AudioSource/youtube/spawner.ts
- src/Util/log.ts
> Fix: only spawn worker in main thread

- .github/dependabot.yml
- remove discord.js from ignores, in configuration targeting master
- add "dependencies" label, in configuration targeting v2
> Chore(dependabot.yml): update depndabot.yml

- src/Commands/seek.ts
> Change(command/seek): change beta to stable

- src/Commands/help.ts
- src/bot.ts
> Fix(command/help): failure of obtaining developer username

- src/Commands/effect.ts
- src/Component/streams/ffmpeg.ts
- src/Component/streams/index.ts
- src/Util/effect.ts
this pr will close #163 
- Effect feature is now stable feature
This PR contains:
- Exposure to command list in order to be able to register effect command as a valid slash command
- internal improvement
- Let the level of bass boost lower to prevent from clipping audio
> Feat: effect feature is now stable

- src/Commands/bulkdelete.ts
- src/Component/streams/ffmpeg.ts
> Feat: bulk delete messages from the bot

- src/AudioSource/youtube/strategies/play-dl.ts
- src/AudioSource/youtube/strategies/youtube-dl.ts
- src/Component/PlayManager.ts
> Fix: could not play live stream

- .github/dependabot.yml
- discord-api-types
- @discordjs/builders
> Chore(dependabot.yml): remove some deps from ignore

- .eslintrc.json
- package-lock.json
- package.json
- src/Component/QueueManager.ts
- src/Structure/GuildDataContainer.ts
- src/bot.ts
> Fix: lock functions that must not running at same time

- src/Commands/import.ts
- src/Structure/GuildDataContainer.ts
> Fix: make sure to dispose the correct cancellation

- .gitignore
- .vscode/launch.json
- src/AudioSource/niconico.ts
- src/AudioSource/soundcloud.ts
- src/AudioSource/youtube/strategies/youtube-dl.ts
- src/AudioSource/youtube/stream.ts
- src/Component/PlayManager.ts
- src/Component/streams/index.ts
- src/Util/general.ts
> Fix(stream): stream stops unexpectedly before it ends

- src/Component/PlayManager.ts
- src/Component/streams/ffmpeg.ts
> Fix: detect stream finished correctly

- .github/dependabot.yml
- package-lock.json
- package.json
> Chore: remove unneeded package

- src/AudioSource/youtube/strategies/index.ts
- src/AudioSource/youtube/strategies/youtube-dl.ts
- src/Commands/bgm.ts
- src/Commands/bulkdelete.ts
- src/Commands/effect.ts
- src/Commands/frame.ts
- src/Commands/news.ts
- src/Commands/search.ts
- src/Commands/searchb.ts
- src/Commands/searchs.ts
- src/Commands/seek.ts
- src/Commands/skip.ts
- src/Component/PlayManager.ts
- src/Component/QueueManager.ts
- src/Structure/GuildDataContainer.ts
- src/Util/general.ts
- src/Util/log.ts
* and overall improvement of error handling
close #475
> Fix: exposing project paths on error

- src/Util/config.ts
> Feat: check some config properties is resolvable as snowflake

- src/Commands/queue.ts
- src/Component/PageToggle.ts
- src/Component/QueueManager.ts
- src/bot.ts
- src/botBase.ts
> Fix: unexpected `null` in command list

- src/botBase.ts
> Fix(command/reset): add guild to list to be backed up

- src/Component/Backupper.ts
- src/Component/PlayManager.ts
- src/Structure/GuildDataContainer.ts
- src/bot.ts
- src/botBase.ts
> Feat: backup volume value

- src/Component/QueueManager.ts
- src/Structure/GuildDataContainer.ts
> Fix: failing to consume playlist

- docs/docs/docs/installation/2-configure.md
> Docs: fix typo

- util/notification.js
> Chore: prevent from sending when not master

- .dockerignore
- .github/workflows/build-docker.yml
- Dockerfile
なんと公式に Docker サポート！？
ドキュメントが必要なら書きます
書いてくれるならコメントに書きます
他に何か必要なものがあればなんでも言ってね
> Feat(Docker): add Docker support

- .github/workflows/build-docker.yml
This reverts commit edae88fb2294245e451694d2f32c3a466ea542c3.
> Revert: "Chore(build-docker.yml): upload artifact (#706)"

- src/Component/Backupper.ts
- src/Component/RateLimitController.ts
- src/Component/streams/index.ts
- src/Util/time.ts
- src/bot.ts
- src/botBase.ts
> Improve: replace object literal with map

- src/AudioSource/custom.ts
- src/AudioSource/fs.ts
- src/AudioSource/googledrive.ts
- src/Component/PlayManager.ts
- src/Util/addon.ts
- src/bot.ts
> Improve: replace eslint-disable comments with plain comment

- .eslintrc.json
- .vscode/settings.json
- src/AudioSource/bestdori.ts
- src/Commands/bgm.ts
- src/Commands/news.ts
- src/Commands/search.ts
- src/Commands/searchb.ts
- src/Commands/searchs.ts
- src/Commands/thumbnail.ts
- src/Component/QueueManager.ts
- src/Component/SearchPanel.ts
- src/Structure/GuildDataContainer.ts
- src/Util/eris/interaction.ts
- src/Util/general.ts
- src/bot.ts
- tsconfig.json
change and improve search panel bahavior
this will close #700 
- improve internal storing structure
- change overall handling
- able to create a search panel a user
> Change: search panel

- src/Commands/import.ts
- src/Commands/play.ts
- src/Component/QueueManager.ts
- src/Structure/GuildDataContainer.ts
- src/bot.ts
> Feat: cancel the last song added by play command

- src/Commands/rm.ts
> Fix(command/rm): fix a bug reading already removed item

- src/bot.ts
> Feat: disconnect if less than 10sec audio is left

- package-lock.json
- package.json
- src/AudioSource/youtube/strategies/ytdl-core.ts
- src/AudioSource/youtube/stream.ts
- src/Component/streams/ffmpeg.ts
- src/dangerouslyRequireOverride.ts
- src/index.ts
close #813 
- fix interruption of playing a long live stream
- fix residue stream that will never be disposed (which prevents from memory leaks)
> Fix: interrupt playing long live stream

- .vscode/launch.json
- .vscode/tasks.json
- Dockerfile
* enable source maps only in development
* disable source maps on docker building
> Chore: configure source maps on development

- config.json.sample
- docs/docs/docs/installation/configuration.md
- docs/docs/docs/permission.md
- src/Component/SearchPanel.ts
- src/Util/config.ts
> Feat: improve executing without message content intent

- src/Commands/effect.ts
- src/Component/PlayManager.ts
- src/bot.ts
> Feat: wait for a while until disconnecting

- src/AudioSource/youtube/index.ts
- src/Commands/queue.ts
- src/Component/PlayManager.ts
- src/Component/QueueManager.ts
- src/Util/time.ts
> Fix: invalid eta when queue including live stream

- src/botBase.ts
> Fix: connecting and paused guild count was always zero

- docs/i18n/ja/docusaurus-plugin-content-docs/current.json
- docs/i18n/ja/docusaurus-theme-classic/footer.json
- docs/i18n/ja/docusaurus-theme-classic/navbar.json
- docs/src/css/custom.css
* bump footer year
* apply custom web font to whole website
> Docs: bump footer year

- README.md
> Docs(README): add additional badges

- src/Commands/reset.ts
- src/Component/PlayManager.ts
> Fix: surely destroy stream

- src/Commands/commands.ts
- src/Component/SearchPanel.ts
> Fix: slash command compatible text

- src/Commands/systeminfo.ts
> Fix(command/systeminfo): fix logs exceeding max description length

- .vscode/settings.json
- src/Commands/invoke.ts
- src/Component/PlayManager.ts
- src/Component/streams/ffmpeg.ts
- src/Component/streams/index.ts
- src/Component/streams/normalizer.ts
- tsconfig.json
* new module, verbose logging the stream
* new normalizer stream
* The size of the buffer that enables smooth playbacks decreased to 1MB (from 2MB)
* Abolish verbose buffer chain
related to #905, #906
> **Warning**  
> This PR may potentially break playing system!
> Must pay attention to be released!
> Feat: verbose stream logging

- src/bot.ts
> Change: decrease timeout duration after leaving voice members

- src/Component/PlayManager.ts
- src/bot.ts
> Feat: leave when all voice members leaved

- src/Commands/commands.ts
- src/Component/PageToggle.ts
- src/Component/QueueManager.ts
- src/Structure/GuildDataContainer.ts
and eliminate meaningless message sending
> Improve: organize page toggles on events

- src/bot.ts
> Feat(bgm): start playing bgm on join in idle state

- package-lock.json
- package.json
- src/@types/spotify-url-info.d.ts
- src/AudioSource/audiosource.ts
- src/AudioSource/fs.ts
- src/AudioSource/index.ts
- src/AudioSource/resolver.ts
- src/AudioSource/spotify.ts
- src/Component/PlayManager.ts
- src/Component/QueueManager.ts
- src/Structure/GuildDataContainer.ts
close #830 
Note: this feature is now still in beta phase.
Note: this feature is currenctly available in Node.js v14+.
> Feat: resolve spotify url

- src/Structure/GuildDataContainer.ts
- src/Util/general.ts
> Fix: handle error when processing playlists

- src/Component/streams/normalizer.ts
this PR prevents from memory leaks
> Fix: destroy stream correctly

- src/Component/streams/ffmpeg.ts
- src/Component/streams/index.ts
fix #952 
This reverts commit 4e87124db7aedcda1f2ab27e0690c60d3dbec541.
> Fix: seek not working

- .github/workflows/build-docker.yml
i refered to https://github.com/eve0415/DevTool/commit/6bcb05fd8e4ae74d273439e27d57a56ce9b8f5d9
> Chore(build-docker.yml): retrive as much cache as possible

- Dockerfile
> Chore(Docker): cache npm module

- src/Commands/invoke.ts
- src/Component/PlayManager.ts
> huh this doesn't seem to be a bug fix? yes you might be right at this time hehe
> Fix(dsl): no way to disable logging in memory

- src/AudioSource/youtube/stream.ts
- src/Component/PlayManager.ts
- src/Component/streams/ffmpeg.ts
- src/Component/streams/index.ts
- src/Component/streams/normalizer.ts
- src/Structure/GuildDataContainer.ts
- src/Util/general.ts
> Fix: prevent from memory leaks

- src/AudioSource/index.ts
- src/AudioSource/youtube/index.ts
- src/AudioSource/youtube/spawner.ts
- src/AudioSource/youtube/worker.ts
- src/Commands/play.ts
- src/Util/general.ts
> Improve: refactor worker thread

- package-lock.json
- package.json
- src/Util/config.ts
- src/index.ts
- tsconfig.json
in order to improve editor speed
and some improvements to speed up the editor more
> Change: replace zod with @sinclair/typebox

- src/AudioSource/youtube/index.ts
* fix the bug no reaction when using `nowplaying` command
> Fix: handle  too large or short description

- src/Commands/uptime.ts
* not update the bound channel when using the `uptime` command
* replace `+` operator with template literal for performance concerns
* change the each title on embed into more suit one
> Fix(commands/uptime): not updating the bound channel

- src/AudioSource/youtube/strategies/index.ts
> Fix: not logging failing to load optional module when debug is off

- .github/workflows/build-docker.yml
- Dockerfile
- package-lock.json
- package.json
commitlint is no longer needed
> Chore: remove commitlint

- test/spotify.test.js
> Chore(test): add test for spotify

- src/AudioSource/spotify.ts
> Fix: improve music evaluation on spotify

- src/Component/QueueManager.ts
> Fix: shuffle spoils equally-playback

- src/@types/node.d.ts
- src/AudioSource/resolver.ts
- src/Commands/help.ts
- src/Component/CommandManager.ts
- src/Structure/GuildDataContainer.ts
- src/Util/config.ts
- src/Util/general.ts
> Feat: disable sources whenever and whatever you want to

- src/Structure/GuildDataContainer.ts
> Feat: more customizable prefix

- docs/docs/docs/feature/addon.md
- docs/docs/docs/installation/configuration.md
- docs/docs/docs/installation/glitch.md
- docs/docs/docs/installation/heroku.md
- docs/docs/docs/installation/replit.md
> docs: better file title on embeds

- Dockerfile
> Chore(Docker): fix cert problems

- docs/i18n/ja/code.json
- docs/i18n/ja/docusaurus-plugin-content-docs/current.json
translate version labels and so on
> Docs: improve ui

- src/Component/QueueManager.ts
- src/Structure/GuildDataContainer.ts
> Feat: cancellable addition from search

- src/AudioSource/spotify.ts
- src/Structure/GuildDataContainer.ts
> Feat: resolvable spotify albums

- src/Component/PlayManager.ts
- src/Component/PlayManagerWithBgm.ts
- src/Structure/GuildDataContainerWithBgm.ts
> Feat: separate bgm volume

- src/AudioSource/audiosource.ts
- src/Commands/search.ts
- src/Component/SearchPanel.ts
- src/Structure/GuildDataContainer.ts
- src/bot.ts
- tsconfig.json
> Feat: search timeout and more cancelable search

- src/Util/config.ts
- test/load-config.test.js
- util/config-for-test.json
Prevent users from running this branch
> Chore: setup trap when debug mode is disabled

- src/index.ts
> Fix: send error log even if debug is on

- src/AudioSource/youtube/strategies/baseYoutubeDlStrategy.ts
- src/AudioSource/youtube/strategies/play-dl.ts
- src/AudioSource/youtube/strategies/ytdl-core.ts
- src/Component/PlayManager.ts
- src/Component/QueueManager.ts
- src/Component/backupper/httpBased.ts
- src/Structure/GuildDataContainer.ts
- src/Util/time.ts
> Remove: custom timer

- util/exec.js
> Fix: broken version detection

- .gitignore
- src/AudioSource/audiosource.ts
- src/AudioSource/custom.ts
- src/AudioSource/googledrive.ts
- src/AudioSource/hibiki.ts
- src/AudioSource/resolver.ts
- src/Commands/import.ts
- src/Component/PlayManager.ts
- src/Component/QueueManager.ts
- src/Component/SourceCache.ts
- src/botBase.ts
- src/config/type.ts
- test/load-config.test.js
- util/config-for-test.json
> Feat: source caching

- src/Util/discord.ts
- src/handlers/commandInteraction.ts
> Feat: use various text channel in server

- src/AudioSource/resolver.ts
- src/AudioSource/spotify.ts
- src/Commands/play.ts
- src/Commands/search.ts
- src/Component/SourceCache.ts
* cache search result
* change compression method
> Feat: caching behavior

- crowdin.yml
> Chore(crowdin.yml): update configuration

- locales/ja/components.json
- src/Component/PlayManager.ts
- src/Component/QueueManager.ts
- src/Component/streams/ffmpeg.ts
- src/Util/time.ts
- src/events/messageCreate.ts
> Fix: player bugs

- src/Commands/reset.ts
- src/Component/backupper/mongodb.ts
- src/Component/backupper/replit.ts
- src/bot.ts
- src/events/guildDelete.ts
SSIA; I'll debug these changes someday ™️
> Feat: delete guild data on guild deletion

- src/Component/QueueManager.ts
> Fix: show messages in correct language

- .github/workflows/fix-lint-errors.yml
* Chore: fix lint errors automatically
* commit author
> Chore: fix lint errors automatically

- .github/workflows/minor-release.yml
- .github/workflows/patch-release.yml
(cherry picked from commit 221e48229c984202495cc2ac55c93a62f5c80efc)
> Update(action): bump peter-evans/create-pull-request from 4 to 5 (#1364) (cherry-picked)

- src/Component/QueueManager.ts
> Fix: handle error while canceling removing last added song

- README.md
Reverts mtripg6666tdr/Discord-SimpleMusicBot#1413
> Revert "Docs: add en-GB link"

- crowdin.yml
Reverts mtripg6666tdr/Discord-SimpleMusicBot#1416
> Revert "Chore(crowdin.yml): change mapping of localized README files"

- docs/package-lock.json
- docs/package.json
Reverts mtripg6666tdr/Discord-SimpleMusicBot#1523
> Revert: "Update(docs): Bump prism-react-renderer from 1.3.5 to 2.0.3 in /docs"

- src/Structure/GuildDataContainer.ts
- src/Structure/LogEmitter.ts
- src/Util/index.ts
- src/logger.ts
> Fix: wrong logging tags

- src/AudioSource/spotify.ts
- src/Structure/GuildDataContainer.ts
> Feat: expand spotify shorten links

- src/Util/index.ts
> Feat: support flac audio as custom stream

- src/Component/PlayManager.ts
- src/Util/index.ts
> Fix: behavior of getting private file urls

- src/events/voiceChannelLeave.ts
> Feat: count voicemembers with excluding bots on voiceChannelLeave event

- package-lock.json
- package.json
- src/Commands/bulk_delete.ts
- src/Commands/import.ts
- src/Commands/index.ts
- src/Commands/play_private.ts
- src/Component/CommandManager.ts
- src/Component/QueueManager.ts
- src/Component/collectors/InteractionCollector.ts
- src/Component/collectors/InteractionCollectorManager.ts
- src/Component/collectors/Pagenation.ts
- src/Structure/GuildDataContainer.ts
- src/Util/discord.ts
- src/handlers/buttonInteraction.ts
* cherry-picked from https://github.com/mtripg6666tdr/Discord-SimpleMusicBot/pull/1696
* cherry-picked from https://github.com/mtripg6666tdr/Discord-SimpleMusicBot/pull/1704
* fix building
> Update: bump oceanic.js from 1.6.0 to 1.7.0

- package-lock.json
- package.json
close #1663 
* this dep is no longer needed
> Chore: remove @types/follow-redirects

- src/Component/PlayManager.ts
> Fix(player): must set preparing flag to false when aborted

- test/spotify.test.js
Too many false positives waste time of ci review.
> Chore(test): disable spotify test for playlist

- src/AudioSource/spotify.ts
> Fix(spotify): new kind of url and broken search on fallback searching

- src/Commands/help.ts
- src/Commands/lyrics.ts
- src/Component/QueueManager.ts
- src/Component/QueueManagerWithBGM.ts
- src/Util/discord.ts
> Fix: issue for new username system

- src/Component/PlayManagerWithBgm.ts
- src/Structure/GuildDataContainerWithBgm.ts
> Fix(bgm): confusing flags on params of PlayManager#play

- src/AudioSource/twitter.ts
> Fix(twitter): play twitter videos

- src/AudioSource/custom.ts
- src/Util/index.ts
Ref: https://discord.com/channels/847435307582095360/895689093952962570/1155164140843843645
> Fix: custom stream abort

- src/AudioSource/youtube/index.ts
* in order to reduce errors
close #1869
> Change: disable cache if it is stale

- .eslintrc.json
- .vscode/tasks.json
- package-lock.json
- package.json
- src/AudioSource/youtube/playlist.ts
- src/AudioSource/youtube/worker.ts
- src/Commands/news.ts
- src/Component/backupper/mongodb.ts
- src/Component/binaryManager.ts
- src/Component/commandManager.ts
- src/Structure/GuildDataContainer.ts
> Feat: use distube/ytpl if available

- package-lock.json
- package.json
- src/index.ts
- src/polyfill.ts
> Feat: support node v16 by polyfill

- src/Component/playManager.ts
- src/events/voiceChannelLeave.ts
> Feat: automatically disconnect when paused

- package-lock.json
This PR fixes a vulnerability issue of ip (<https://github.com/advisories/GHSA-2p57-rm9w-gvfp>)
> Chore(deps): update socks from 2.7.1 to 2.8.3

- src/AudioSource/audiosource.ts
- src/AudioSource/niconico.ts
- src/Component/streams/ffmpeg.ts
* Play niconico video correctly
> Feat: play niconico video

- src/Component/rateLimitController.ts
- src/bot.ts
- src/botBase.ts
- src/events/interactionCreate.ts
- src/events/messageCreate.ts
- src/events/ready.ts
- src/types/rateLimitController.ts
> Fix: accidentally ratelimiting when chatting without bot

- src/Component/queueManager.ts
> Fix: apply equal playback when removing or moving songs

- src/AudioSource/youtube/index.ts
- src/Component/playManager.ts
- src/Component/queueManager.ts
- src/Util/index.ts
> Feat: smoother playback

- src/Commands/frame.ts
- src/Component/playManager.ts
- src/Util/time.ts
followup ~~actual~~ fix for #2430
> Fix: actual fix for weird time

- src/Commands/play_private.ts
- src/Structure/GuildDataContainer.ts
Songs added incorrect position (for instance, at the top of the queue) in some situation
> Fix: songs added in incorrect position in queue

- src/Commands/equalplayback.ts
- src/Component/queueManager.ts
- src/Structure/GuildDataContainer.ts
* Fix the cancel button behavior when equalplayback enabled
* Sort when equalplayback enabled
> Fix: overall behavior when equalplayback enabled

- src/Component/playManager.ts
* Suppress adding when finishing preparing to play an user-added item
> Fix: prevent adding a new radio item when added-by is null

- docs/docs/setup/installation/normal.md
- docs/docs/setup/support.md
- docs/versioned_docs/version-v4.3/setup/installation/normal.md
since v4.3, node.js v16.4 or later is supported
> Docs: update node version

- package-lock.json
- package.json
- src/Util/index.ts
- src/events/ready.ts
Fixed: YouTube playback issue.
> Update: @distube/ytdl-core from 4.14.4 to 4.15.9

- .github/workflows/build-docker.yml
- Dockerfile
Also fixes failing to buld docker image on arm64 (closes #2820)
> Chore(Dockerfile): update base image from bullseye to bookworm

- src/Commands/invoke.ts
> Fix(commands/invoke): wrong parsing of special commands
